name: Build (OpenBSD)

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build_openbsd:
    name: Build on ${{ matrix.box }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        box:
          - generic/openbsd7
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Provision VM
      uses: hummeltech/openbsd-vagrant-action@v2
      with:
        box: ${{ matrix.box }}
        save_box_to_cache: true

    - name: Install packages
      run: sudo pkg_add -I cmake python3

    - name: Generate build system
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX="" -DLIBCPUID_ENABLE_TESTS=ON

    - name: Build
      run: cmake --build build

    - name: Run cpuid_tool
      run: ./build/cpuid_tool/cpuid_tool --save=- --all

    - name: Run tests
      run: |
        make -C build consistency
        make -C build test-old

    - name: Install
      run: cmake --install build
      env:
        DESTDIR: ${{ github.workspace }}/installdir
